services:
  mehmetcanwt:
    container_name: mehmetcanwt
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEB_KEY=${WEB_KEY}
      - NODE_ENV=production
    networks:
      - mehmetcanwt-net

networks:
  mehmetcanwt-net:
    driver: bridge