services:
  migration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mehmetcanwt-migration
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: ["bun", "run", "db:push"]
    networks:
      - mehmetcanwt-net

  mehmetcanwt:
    container_name: mehmetcanwt
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      migration:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEB_KEY=${WEB_KEY}
      - LANYARD_API_KEY=${LANYARD_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - STEAM_ID=${STEAM_ID}
      - DISCORD_ID=${DISCORD_ID}
      - NODE_ENV=production
    networks:
      - mehmetcanwt-net

networks:
  mehmetcanwt-net:
    driver: bridge
